version: '3'
services:
  zone0:
    image: kjarosh/agh-gmmf-prototype:latest
    command: server
    environment:
      ZONE_ID: zone0
    networks:
      intranet:
    ports:
      - "8080:80"
      - "8780:8080"
      - "9010:9010"

  zone1:
    image: kjarosh/agh-gmmf-prototype:latest
    command: server
    environment:
      ZONE_ID: zone1
    networks:
      intranet:
    ports:
      - "8081:80"
      - "8781:8080"
      - "9011:9010"

  zone2:
    image: kjarosh/agh-gmmf-prototype:latest
    command: server
    environment:
      ZONE_ID: zone2
    networks:
      intranet:
    ports:
      - "8082:80"
      - "8782:8080"
      - "9012:9010"

  client:
    image: kjarosh/agh-gmmf-prototype:latest
    command: client
    stdin_open: true
    tty: true
    networks:
      intranet:

networks:
  intranet:
