FROM openjdk:11

RUN curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && \
    apt-get install -y python3 python3-pip postgresql kubectl tree && \
    apt-get clean && \
    pip3 install numpy matplotlib

COPY docker/run-main.sh run-main.sh
COPY target/agh-pp-simulator-*.jar app.jar
COPY tests/docker/ /

ENTRYPOINT ["./tests-kube.sh"]
