FROM openjdk:11
ENV DEBIAN_FRONTEND=noninteractive

RUN curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && \
    apt-get install -y python3 python3-pip postgresql kubectl tree && \
    apt-get clean && \
    pip3 install numpy matplotlib

COPY zone-simulator/docker/run-main.sh run-main.sh
COPY zone-simulator/target/zone-simulator-*.jar app.jar
COPY tests-k8s/docker/ /

ENTRYPOINT ["./tests-kube.sh"]
